version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://enterprise_user:secure_password@db:5432/enterprise_scanner
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ../../website:/app/website
    networks:
      - enterprise-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=enterprise_scanner
      - POSTGRES_USER=enterprise_user
      - POSTGRES_PASSWORD=secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - enterprise-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - enterprise-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../website:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - enterprise-network

volumes:
  postgres_data:
  redis_data:

networks:
  enterprise-network:
    driver: bridge